// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameProducto = "producto"

// Producto mapped from table <producto>
type Producto struct {
	ID           int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Nombre       string `gorm:"column:nombre;not null" json:"nombre"`
	IDContenedor int32  `gorm:"column:id_contenedor;not null" json:"id_contenedor"`
	Cantidad     int32  `gorm:"column:cantidad;not null" json:"cantidad"`
}

// TableName Producto's table name
func (*Producto) TableName() string {
	return TableNameProducto
}
